/* GENERATED by build_wiki.py — do not hand-edit. */
(function () {
  var input = document.getElementById('wiki-search');
  var results = document.getElementById('search-results');
  var nav = document.querySelector('.nav');
  if (!input || !results || !nav) return;

  var index = [], loaded = false;
  function load() {
    if (loaded) return; loaded = true;
    fetch('search-index.json').then(function (r) { return r.json(); })
      .then(function (d) { index = d; if (input.value.trim()) run(); })
      .catch(function () { index = []; });
  }
  input.addEventListener('focus', load);

  var KIND = { page: 'Topic', section: 'Section', doc: '' };
  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }
  function score(hay, toks) {
    var s = 0;
    for (var i = 0; i < toks.length; i++) {
      var pos = hay.indexOf(toks[i]);
      if (pos < 0) return 0;
      s += (pos === 0 ? 3 : 1) + (hay.indexOf(' ' + toks[i]) >= 0 ? 1 : 0);
    }
    return s;
  }
  function run() {
    var q = input.value.trim().toLowerCase();
    if (!q) { results.hidden = true; nav.hidden = false; results.innerHTML = ''; return; }
    var toks = q.split(/\s+/);
    var hits = index.map(function (e) { return { e: e, s: score(e.hay, toks) }; })
      .filter(function (x) { return x.s > 0; })
      .sort(function (a, b) { return b.s - a.s || a.e.title.length - b.e.title.length; })
      .slice(0, 18);
    if (!hits.length) {
      results.innerHTML = '<div class="sr-empty">No matches</div>';
    } else {
      results.innerHTML = hits.map(function (x) {
        var e = x.e;
        var tag = e.kind === 'doc' ? '' : '<span class="sr-tag">' + KIND[e.kind] + '</span>';
        return '<a class="sr-item" href="' + e.url + '"><span class="sr-title">'
          + esc(e.title) + tag + '</span><span class="sr-sub">' + esc(e.sub || '')
          + '</span></a>';
      }).join('');
    }
    results.hidden = false; nav.hidden = true;
  }
  input.addEventListener('input', run);
  input.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') { input.value = ''; run(); input.blur(); }
    if (e.key === 'Enter') { var f = results.querySelector('.sr-item'); if (f) f.click(); }
  });
  document.addEventListener('keydown', function (e) {
    var t = document.activeElement;
    var typing = t && /input|textarea|select/i.test(t.tagName);
    if (e.key === '/' && !typing) { e.preventDefault(); input.focus(); }
  });
})();
/* Theme toggle */
(function () {
  var btn = document.getElementById('theme-toggle');
  if (!btn) return;
  btn.addEventListener('click', function () {
    var cur = document.documentElement.getAttribute('data-theme') || 'light';
    var next = cur === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    try { localStorage.setItem('wiki-theme', next); } catch (e) {}
  });
})();
/* Scroll progress */
(function () {
  var bar = document.getElementById('scroll-progress');
  if (!bar) return;
  function update() {
    var h = document.documentElement.scrollHeight - window.innerHeight;
    bar.style.width = (h > 0 ? (window.scrollY / h * 100) : 0) + '%';
  }
  window.addEventListener('scroll', update, { passive: true });
  update();
})();
